name: Build

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    workflow_dispatch:

env:
    CARGO_TERM_COLOR: always

jobs:
    qt6:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                ver: [6.5.0]
        env:
            QT_QPA_PLATFORM: offscreen
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - uses: Swatinem/rust-cache@v2
              with:
                  key: rust_cache6

            - name: Install Qt
              uses: jurplel/install-qt-action@v4
              with:
                  version: ${{ matrix.ver }}
                  cache: true

            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: program-artifact
                  path: target/release/program
